export const REDIRECT_URI = 'http://localhost:3000/callback'
export const STATE_LENGTH = 16
export const SESSION_ID_LENGTH = 64
export const SUCCESS_MESSAGE = 'success'
export const FAILURE_MESSAGE = 'failure'
export const COOKIE_NAME = 'google-oauth-demo'
export const CLIENT_ID = process.env.GOOGLE_CLIENT_ID as string
export const CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET as string
export const MONGO_URI = process.env.MONGO_URI as string
export const DB_NAME = process.env.DB_NAME as string
export const USERS_COLLECTION = process.env.USERS_COLLECTION as string
